#!/bin/bash

source caQtDM_Env

echo
echo ========== Collect Files for Mac Bundle ============
echo

chmod 755 ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libca.3.14.12.dylib
chmod 755 ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libCom.3.14.12.dylib

macdeployqt ./caQtDM_Binaries/caQtDM.app

echo
echo ========== change EPICS LIBS ============
echo

install_name_tool -id @executable_path/../Frameworks/libca.3.14.12.dylib ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libca.3.14.12.dylib
install_name_tool -id @executable_path/../Frameworks/libCom.3.14.12.dylib ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libCom.3.14.12.dylib

install_name_tool -change "${EPICSLIB}/libCom.3.14.12.dylib" @executable_path/../Frameworks/libCom.3.14.12.dylib ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libca.3.14.12.dylib
install_name_tool -change libca.3.14.12.dylib @executable_path/../Frameworks/libca.3.14.12.dylib ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libcaQTDM_Lib.dylib

echo
echo ========== change caqtdm ============
echo

install_name_tool -change libcaQtDM_Lib.dylib @executable_path/../Frameworks/libcaQtDM_Lib.dylib ./caQtDM_Binaries/caQtDM.app/Contents/MacOS/caQtDM

echo
echo ========== change libcaQtDM_Lib.dylib ============
echo

install_name_tool -change libqtcontrols.dylib @executable_path/../Frameworks/libqtcontrols.dylib ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libcaQtDM_Lib.dylib

install_name_tool -change "${EPICSLIB}/libCom.3.14.12.dylib" "@executable_path/../Frameworks/libCom.3.14.12.dylib" ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libcaQtDM_Lib.dylib
install_name_tool -change "${EPICSLIB}/libca.3.14.12.dylib" "@executable_path/../Frameworks/libca.3.14.12.dylib" ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libcaQtDM_Lib.dylib

install_name_tool -change "qwt.framework/Versions/6/qwt" "@executable_path/../Frameworks/qwt.framework/Versions/6/qwt" ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libcaQtDM_Lib.dylib

echo
echo ========== change libqtcontrols.dylib ============
echo

install_name_tool -change "qwt.framework/Versions/6/qwt" "@executable_path/../Frameworks/qwt.framework/Versions/6/qwt" ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libqtcontrols.dylib


echo
echo ========== change libqtcontrols_controllers_plugin.dylib ============
echo

install_name_tool -change libqtcontrols.dylib @executable_path/../Frameworks/libqtcontrols.dylib ./caQtDM_Binaries/caQtDM.app/Contents/PlugIns/designer/libqtcontrols_controllers_plugin.dylib  
install_name_tool -change "qwt.framework/Versions/6/qwt" "@executable_path/../Frameworks/qwt.framework/Versions/6/qwt" ./caQtDM_Binaries/caQtDM.app/Contents/PlugIns/designer/libqtcontrols_controllers_plugin.dylib 


echo
echo ========== change libqtcontrols_graphics_plugin.dylib ============
echo

install_name_tool -change libqtcontrols.dylib @executable_path/../Frameworks/libqtcontrols.dylib ./caQtDM_Binaries/caQtDM.app/Contents/PlugIns/designer/libqtcontrols_graphics_plugin.dylib
install_name_tool -change "qwt.framework/Versions/6/qwt" "@executable_path/../Frameworks/qwt.framework/Versions/6/qwt" ./caQtDM_Binaries/caQtDM.app/Contents/PlugIns/designer/libqtcontrols_graphics_plugin.dylib

echo
echo ========== change libqtcontrols_monitors_plugin.dylib ============
echo

install_name_tool -change libqtcontrols.dylib @executable_path/../Frameworks/libqtcontrols.dylib ./caQtDM_Binaries/caQtDM.app/Contents/PlugIns/designer/libqtcontrols_monitors_plugin.dylib
install_name_tool -change "qwt.framework/Versions/6/qwt" "@executable_path/../Frameworks/qwt.framework/Versions/6/qwt" ./caQtDM_Binaries/caQtDM.app/Contents/PlugIns/designer/libqtcontrols_monitors_plugin.dylib

echo
echo ========== mkdir Applications/Frameworks ============
echo

mkdir ./caQtDM_Binaries/caQtDM.app/Contents/Applications


echo
echo ========== add designer.app ============
echo

cp -R ${QTHOME}/bin/Designer.app ./caQtDM_Binaries/caQtDM.app/Contents/Applications/
mkdir ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/Frameworks/


cp ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/libqtcontrols.dylib ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/Frameworks/
cp -R ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/qwt.framework ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/Frameworks/
cp -R ./caQtDM_Binaries/caQtDM.app/Contents/Frameworks/QtSvg.framework ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/Frameworks/


mkdir ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/PlugIns
mkdir ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/PlugIns/designer

cp ./caQtDM_Binaries/designer/*.dylib ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/PlugIns/designer/
macdeployqt ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app
install_name_tool -change "qwt.framework/Versions/6/qwt" "@executable_path/../Frameworks/qwt.framework/Versions/6/qwt" ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/PlugIns/designer/libqtcontrols_controllers_plugin.dylib 
install_name_tool -change "qwt.framework/Versions/6/qwt" "@executable_path/../Frameworks/qwt.framework/Versions/6/qwt" ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/PlugIns/designer/libqtcontrols_graphics_plugin.dylib
install_name_tool -change "qwt.framework/Versions/6/qwt" "@executable_path/../Frameworks/qwt.framework/Versions/6/qwt" ./caQtDM_Binaries/caQtDM.app/Contents/Applications/Designer.app/Contents/PlugIns/designer/libqtcontrols_monitors_plugin.dylib


echo
echo ========== add adl2ui.app ============
echo

cp -R ./caQtDM_Binaries/adl2ui.app ./caQtDM_Binaries/caQtDM.app/Contents/Applications/
macdeployqt ./caQtDM_Binaries/caQtDM.app/Contents/Applications/adl2ui.app

#cd caQtDM_Binaries
#macdeployqt caQtDM.app -dmg
echo
echo ========== modifiy dmg image ============
echo
hdiutil create -format UDRW ./caQtDM_Binaries/caqtdm.dmg -srcfolder ./caQtDM_Binaries/caQtDM.app
hdiutil attach -readwrite ./caQtDM_Binaries/caQtDM.dmg
ln -s /Applications /Volumes/caQtDM/Applications
hdiutil detach /Volumes/caQtDM/

cd ..