#!/bin/bash

source caQtDM_Env

echo  $CAQTDM_COLLECT will be removed and all directories will be cleaned up

read -p "Press [Enter] key to start cleanup "

echo ========== remove binaries from directories ============
if [ -d "$CAQTDM_COLLECT" ]; then
rm -rf $CAQTDM_COLLECT
fi

echo ========== remove makefiles from directories ============
rm -f ./Makefile
rm -f ./caQtDM_Viewer/Makefile
rm -f ./caQtDM_Viewer/parser/Makefile
rm -f ./caQtDM_Viewer/parserEDM/Makefile
rm -f ./caQtDM_Parsers/Makefile
rm -f ./caQtDM_Parsers/adlParser/Makefile
rm -f ./caQtDM_Parsers/edlParser/Makefile
rm -f ./caQtDM_AndroidFunctions/Makefile
rm -f ./caQtDM_Lib/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/demo/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/demo/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics3/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics3/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics4/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics4/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/bsread/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/bsread/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveSF/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveSF/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archivePRO/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archivePRO/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveHIPA/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveHIPA/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveHTTP/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveHTTP/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveCA/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveCA/Makefile
rm -f ./caQtDM_QtControls/Makefile
rm -f ./caQtDM_QtControls/plugins/Makefile
rm -f ./caQtDM_Lib/*.so
rm -f ./caQtDM_QtControls/*.so
rm -f ./caQtDM_QtControls/plugins/*.so

echo ========== remove moc/obj from directories ============
rm -f ./caQtDM_QtControls/plugins/moc/*
rm -f ./caQtDM_QtControls/plugins/obj/*
rm -f ./caQtDM_QtControls/moc/*
rm -f ./caQtDM_QtControls/obj/*
rm -f ./caQtDM_Lib/obj/*
rm -f ./caQtDM_Lib/moc/*

rm -f ./caQtDM_Parsers/Makefile
rm -f ./caQtDM_Parsers/adlParserSharedLib/Makefile
rm -f ./caQtDM_Parsers/adlParserStaticLib/Makefile
rm -f ./caQtDM_Parsers/edlParserSharedLib/Makefile
rm -f ./caQtDM_Parsers/edlParserStaticLib/Makefile
rm -f ./caQtDM_Parsers/adlParserSharedLib/obj/*
rm -f ./caQtDM_Parsers/adlParserStaticLib/obj/*
rm -f ./caQtDM_Parsers/edlParserSharedLib/obj/*
rm -f ./caQtDM_Parsers/edlParserStaticLib/obj/*
rm -f ./caQtDM_Parsers/adlParserSharedLib/moc/*
rm -f ./caQtDM_Parsers/adlParserStaticLib/moc/*
rm -f ./caQtDM_Parsers/edlParserSharedLib/moc/*
rm -f ./caQtDM_Parsers/edlParserStaticLib/moc/*

rm -f ./caQtDM_Lib/caQtDM_Plugins/demo/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/demo/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics3/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics3/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics4/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics4/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/bsread/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/bsread/moc/*

rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveSF/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveSF/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveHIPA/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveHIPA/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveHTTP/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveHTTP/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archivePRO/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archivePRO/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveCA/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/archive/archiveCA/moc/*

rm -f ./caQtDM_Viewer/obj/*
rm -f ./caQtDM_Viewer/moc/*
rm -f ./caQtDM_Viewer/parser/moc/*
rm -f ./caQtDM_Viewer/parser/obj/*
rm -f ./caQtDM_Viewer/parserEDM/moc/*
rm -f ./caQtDM_Viewer/parserEDM/obj/*

echo =========== clean all ==================
qmake all.pro
make distclean


