#!/bin/sh
QTBASE=/usr/local/Trolltech/$EPICS_HOST_ARCH
DESTINATION=$QTBASE/binQt/
SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries

install -v $SOURCE/caQtDM $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries
install -v $SOURCE/adl2ui $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries
install -v $SOURCE/lib* $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries/designer
DESTINATION=$QTBASE/Qt-4.8.2/plugins/designer/
install -v $SOURCE/lib* $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries/controlsystems
DESTINATION=$QTBASE/binQt/controlsystems
install -v $SOURCE/lib* $DESTINATION
