#!/bin/bash

source caQtDM_Env

echo package will be removed from ./caQtDM_Binaries and all directories will be cleaned up

read -p "Press [Enter] key to start cleanup "

echo ========== remove binaries from directories ============
if [ -d "./caQtDM_Binaries" ]; then
rm -rf ./caQtDM_Binaries/*
fi

echo ========== remove makefiles from directories ============
rm -f ./Makefile
rm -f ./caQtDM_Viewer/Makefile
rm -f ./caQtDM_Viewer/parser/Makefile
rm -f ./caQtDM_Viewer/parserEDM/Makefile
rm -f ./caQtDM_Lib/Makefile
rm -f ./caQtDM_Lib/caQtDM_Plugins/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/demo/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics3/Makefile.csplugins
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics4/Makefile.csplugins
rm -f ./caQtDM_QtControls/Makefile
rm -f ./caQtDM_QtControls/plugins/Makefile
rm -f ./caQtDM_Lib/*.so
rm -f ./caQtDM_QtControls/*.so
rm -f ./caQtDM_QtControls/plugins/*.so

echo ========== remove moc/obj from directories ============
rm -f ./caQtDM_QtControls/plugins/moc/*
rm -f ./caQtDM_QtControls/plugins/obj/*
rm -f ./caQtDM_QtControls/moc/*
rm -f ./caQtDM_QtControls/obj/*
rm -f ./caQtDM_Lib/obj/*
rm -f ./caQtDM_Lib/moc/*

rm -f ./caQtDM_Lib/caQtDM_Plugins/demo/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/demo/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics3/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics3/moc/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics4/obj/*
rm -f ./caQtDM_Lib/caQtDM_Plugins/epics4/moc/*

rm -f ./caQtDM_Viewer/obj/*
rm -f ./caQtDM_Viewer/moc/*
rm -f ./caQtDM_Viewer/parser/moc/*
rm -f ./caQtDM_Viewer/parser/obj/*
rm -f ./caQtDM_Viewer/parserEDM/moc/*
rm -f ./caQtDM_Viewer/parserEDM/obj/*

echo =========== clean all ==================
qmake all.pro
make distclean


