#!/bin/sh
QTBASE=/usr/local/Trolltech/$EPICS_HOST_ARCH
DESTINATION=$QTBASE/binQt/
SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries

cp -v $SOURCE/caQtDM $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries
cp -v $SOURCE/adl2ui $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries
cp -v $SOURCE/lib* $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/QtTunes
cp -v $SOURCE/QtTunes $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/HFdispQt
cp -v $SOURCE/caHFdispQt /home/ACS/Control/Bin/

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/probeQtProscan
cp -v $SOURCE/probeQt $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries/designer
DESTINATION=$QTBASE/Qt-4.8.2/plugins/designer/
cp -v $SOURCE/lib* $DESTINATION

SOURCE=/afs/psi.ch/user/m/mezger/workarea/ACS/mezger/caQtDM_Project/caQtDM_Binaries/controlsystems
DESTINATION=$QTBASE/Qt-4.8.2/plugins/controlsystems/
cp -v $SOURCE/lib* $DESTINATION


