#############################################################################
# Makefile for building: all
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sat Apr 10 13:24:44 2021
# Project:  all.pro
# Template: subdirs
# Command: /usr/lib64/qt4/bin/qmake -o Makefile all.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib64/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-caQtDM_QtControls \
		sub-caQtDM_Lib \
		sub-caQtDM_Viewer \
		sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro \
		sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro \
		sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro \
		sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro \
		sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro \
		sub-caQtDM_Parsers \
		sub-caQtDM_Viewer-parser-parser-pro \
		sub-caQtDM_Viewer-parserEDM-parserEDM-pro

caQtDM_QtControls/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/ || $(MKDIR) caQtDM_QtControls/ 
	cd caQtDM_QtControls/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/caQtDM_QtControls.pro -o $(MAKEFILE)
sub-caQtDM_QtControls-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/ || $(MKDIR) caQtDM_QtControls/ 
	cd caQtDM_QtControls/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/caQtDM_QtControls.pro -o $(MAKEFILE)
sub-caQtDM_QtControls: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers FORCE
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE)
sub-caQtDM_QtControls-make_default: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers-make_default FORCE
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE) 
sub-caQtDM_QtControls-make_first: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers-make_first FORCE
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE) first
sub-caQtDM_QtControls-all: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers-all FORCE
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE) all
sub-caQtDM_QtControls-clean: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers-clean FORCE
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE) clean
sub-caQtDM_QtControls-distclean: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers-distclean FORCE
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE) distclean
sub-caQtDM_QtControls-install_subtargets: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers-install_subtargets FORCE
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE) install
sub-caQtDM_QtControls-uninstall_subtargets: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers-uninstall_subtargets FORCE
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE) uninstall
caQtDM_Lib/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) caQtDM_Lib/ || $(MKDIR) caQtDM_Lib/ 
	cd caQtDM_Lib/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Lib/caQtDM_Lib.pro -o $(MAKEFILE)
sub-caQtDM_Lib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_Lib/ || $(MKDIR) caQtDM_Lib/ 
	cd caQtDM_Lib/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Lib/caQtDM_Lib.pro -o $(MAKEFILE)
sub-caQtDM_Lib: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls FORCE
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE)
sub-caQtDM_Lib-make_default: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls-make_default FORCE
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE) 
sub-caQtDM_Lib-make_first: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls-make_first FORCE
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE) first
sub-caQtDM_Lib-all: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls-all FORCE
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE) all
sub-caQtDM_Lib-clean: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls-clean FORCE
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-caQtDM_Lib-distclean: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls-distclean FORCE
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-caQtDM_Lib-install_subtargets: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls-install_subtargets FORCE
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE) install
sub-caQtDM_Lib-uninstall_subtargets: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls-uninstall_subtargets FORCE
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE) uninstall
caQtDM_Viewer/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) caQtDM_Viewer/ || $(MKDIR) caQtDM_Viewer/ 
	cd caQtDM_Viewer/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Viewer/caQtDM_Viewer.pro -o $(MAKEFILE)
sub-caQtDM_Viewer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_Viewer/ || $(MKDIR) caQtDM_Viewer/ 
	cd caQtDM_Viewer/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Viewer/caQtDM_Viewer.pro -o $(MAKEFILE)
sub-caQtDM_Viewer: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls \
		sub-caQtDM_Lib \
		sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro \
		sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro \
		sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro \
		sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro \
		sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro FORCE
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE)
sub-caQtDM_Viewer-make_default: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls-make_default sub-caQtDM_Lib-make_default sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-make_default sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-make_default sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-make_default sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-make_default sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-make_default FORCE
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE) 
sub-caQtDM_Viewer-make_first: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls-make_first sub-caQtDM_Lib-make_first sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-make_first sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-make_first sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-make_first sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-make_first sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-make_first FORCE
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE) first
sub-caQtDM_Viewer-all: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls-all sub-caQtDM_Lib-all sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-all sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-all sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-all sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-all sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-all FORCE
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE) all
sub-caQtDM_Viewer-clean: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls-clean sub-caQtDM_Lib-clean sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-clean sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-clean sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-clean sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-clean sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-clean FORCE
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-caQtDM_Viewer-distclean: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls-distclean sub-caQtDM_Lib-distclean sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-distclean sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-distclean sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-distclean sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-distclean sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-distclean FORCE
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-caQtDM_Viewer-install_subtargets: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls-install_subtargets sub-caQtDM_Lib-install_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-install_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-install_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-install_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-install_subtargets sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-install_subtargets FORCE
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE) install
sub-caQtDM_Viewer-uninstall_subtargets: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls-uninstall_subtargets sub-caQtDM_Lib-uninstall_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-uninstall_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-uninstall_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-uninstall_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-uninstall_subtargets sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-uninstall_subtargets FORCE
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE) uninstall
caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers: 
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/plugins/ || $(MKDIR) caQtDM_QtControls/plugins/ 
	cd caQtDM_QtControls/plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/plugins/qtcontrols_controllers.pro -o $(MAKEFILE).qtcontrols_controllers
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/plugins/ || $(MKDIR) caQtDM_QtControls/plugins/ 
	cd caQtDM_QtControls/plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/plugins/qtcontrols_controllers.pro -o $(MAKEFILE).qtcontrols_controllers
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls \
		sub-caQtDM_Lib FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-make_default: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls-make_default sub-caQtDM_Lib-make_default FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers 
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-make_first: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls-make_first sub-caQtDM_Lib-make_first FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers first
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-all: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls-all sub-caQtDM_Lib-all FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers all
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-clean: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls-clean sub-caQtDM_Lib-clean FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers clean
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-distclean: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls-distclean sub-caQtDM_Lib-distclean FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers distclean
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-install_subtargets: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls-install_subtargets sub-caQtDM_Lib-install_subtargets FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers install
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-uninstall_subtargets: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls-uninstall_subtargets sub-caQtDM_Lib-uninstall_subtargets FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers uninstall
caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics: 
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/plugins/ || $(MKDIR) caQtDM_QtControls/plugins/ 
	cd caQtDM_QtControls/plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/plugins/qtcontrols_graphics.pro -o $(MAKEFILE).qtcontrols_graphics
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/plugins/ || $(MKDIR) caQtDM_QtControls/plugins/ 
	cd caQtDM_QtControls/plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/plugins/qtcontrols_graphics.pro -o $(MAKEFILE).qtcontrols_graphics
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls \
		sub-caQtDM_Lib FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-make_default: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls-make_default sub-caQtDM_Lib-make_default FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics 
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-make_first: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls-make_first sub-caQtDM_Lib-make_first FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics first
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-all: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls-all sub-caQtDM_Lib-all FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics all
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-clean: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls-clean sub-caQtDM_Lib-clean FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics clean
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-distclean: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls-distclean sub-caQtDM_Lib-distclean FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics distclean
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-install_subtargets: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls-install_subtargets sub-caQtDM_Lib-install_subtargets FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics install
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-uninstall_subtargets: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls-uninstall_subtargets sub-caQtDM_Lib-uninstall_subtargets FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics uninstall
caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors: 
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/plugins/ || $(MKDIR) caQtDM_QtControls/plugins/ 
	cd caQtDM_QtControls/plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/plugins/qtcontrols_monitors.pro -o $(MAKEFILE).qtcontrols_monitors
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/plugins/ || $(MKDIR) caQtDM_QtControls/plugins/ 
	cd caQtDM_QtControls/plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/plugins/qtcontrols_monitors.pro -o $(MAKEFILE).qtcontrols_monitors
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls \
		sub-caQtDM_Lib FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-make_default: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls-make_default sub-caQtDM_Lib-make_default FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors 
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-make_first: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls-make_first sub-caQtDM_Lib-make_first FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors first
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-all: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls-all sub-caQtDM_Lib-all FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors all
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-clean: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls-clean sub-caQtDM_Lib-clean FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors clean
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-distclean: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls-distclean sub-caQtDM_Lib-distclean FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors distclean
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-install_subtargets: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls-install_subtargets sub-caQtDM_Lib-install_subtargets FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors install
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-uninstall_subtargets: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls-uninstall_subtargets sub-caQtDM_Lib-uninstall_subtargets FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors uninstall
caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities: 
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/plugins/ || $(MKDIR) caQtDM_QtControls/plugins/ 
	cd caQtDM_QtControls/plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/plugins/qtcontrols_utilities.pro -o $(MAKEFILE).qtcontrols_utilities
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_QtControls/plugins/ || $(MKDIR) caQtDM_QtControls/plugins/ 
	cd caQtDM_QtControls/plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_QtControls/plugins/qtcontrols_utilities.pro -o $(MAKEFILE).qtcontrols_utilities
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls \
		sub-caQtDM_Lib FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-make_default: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls-make_default sub-caQtDM_Lib-make_default FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities 
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-make_first: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls-make_first sub-caQtDM_Lib-make_first FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities first
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-all: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls-all sub-caQtDM_Lib-all FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities all
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-clean: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls-clean sub-caQtDM_Lib-clean FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities clean
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-distclean: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls-distclean sub-caQtDM_Lib-distclean FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities distclean
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-install_subtargets: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls-install_subtargets sub-caQtDM_Lib-install_subtargets FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities install
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-uninstall_subtargets: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls-uninstall_subtargets sub-caQtDM_Lib-uninstall_subtargets FORCE
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities uninstall
caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins: 
	@$(CHK_DIR_EXISTS) caQtDM_Lib/caQtDM_Plugins/ || $(MKDIR) caQtDM_Lib/caQtDM_Plugins/ 
	cd caQtDM_Lib/caQtDM_Plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Lib/caQtDM_Plugins/csplugins.pro -o $(MAKEFILE).csplugins
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_Lib/caQtDM_Plugins/ || $(MKDIR) caQtDM_Lib/caQtDM_Plugins/ 
	cd caQtDM_Lib/caQtDM_Plugins/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Lib/caQtDM_Plugins/csplugins.pro -o $(MAKEFILE).csplugins
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib FORCE
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-make_default: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib-make_default FORCE
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins 
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-make_first: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib-make_first FORCE
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins first
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-all: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib-all FORCE
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins all
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-clean: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib-clean FORCE
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins clean
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-distclean: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib-distclean FORCE
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins distclean
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-install_subtargets: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib-install_subtargets FORCE
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins install
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-uninstall_subtargets: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib-uninstall_subtargets FORCE
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins uninstall
caQtDM_Parsers/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) caQtDM_Parsers/ || $(MKDIR) caQtDM_Parsers/ 
	cd caQtDM_Parsers/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Parsers/caQtDM_Parsers.pro -o $(MAKEFILE)
sub-caQtDM_Parsers-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_Parsers/ || $(MKDIR) caQtDM_Parsers/ 
	cd caQtDM_Parsers/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Parsers/caQtDM_Parsers.pro -o $(MAKEFILE)
sub-caQtDM_Parsers: caQtDM_Parsers/$(MAKEFILE) FORCE
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE)
sub-caQtDM_Parsers-make_default: caQtDM_Parsers/$(MAKEFILE) FORCE
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE) 
sub-caQtDM_Parsers-make_first: caQtDM_Parsers/$(MAKEFILE) FORCE
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE) first
sub-caQtDM_Parsers-all: caQtDM_Parsers/$(MAKEFILE) FORCE
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE) all
sub-caQtDM_Parsers-clean: caQtDM_Parsers/$(MAKEFILE) FORCE
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE) clean
sub-caQtDM_Parsers-distclean: caQtDM_Parsers/$(MAKEFILE) FORCE
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE) distclean
sub-caQtDM_Parsers-install_subtargets: caQtDM_Parsers/$(MAKEFILE) FORCE
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE) install
sub-caQtDM_Parsers-uninstall_subtargets: caQtDM_Parsers/$(MAKEFILE) FORCE
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE) uninstall
caQtDM_Viewer/parser/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) caQtDM_Viewer/parser/ || $(MKDIR) caQtDM_Viewer/parser/ 
	cd caQtDM_Viewer/parser/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Viewer/parser/parser.pro -o $(MAKEFILE)
sub-caQtDM_Viewer-parser-parser-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_Viewer/parser/ || $(MKDIR) caQtDM_Viewer/parser/ 
	cd caQtDM_Viewer/parser/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Viewer/parser/parser.pro -o $(MAKEFILE)
sub-caQtDM_Viewer-parser-parser-pro: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers FORCE
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE)
sub-caQtDM_Viewer-parser-parser-pro-make_default: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers-make_default FORCE
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE) 
sub-caQtDM_Viewer-parser-parser-pro-make_first: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers-make_first FORCE
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE) first
sub-caQtDM_Viewer-parser-parser-pro-all: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers-all FORCE
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE) all
sub-caQtDM_Viewer-parser-parser-pro-clean: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers-clean FORCE
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE) clean
sub-caQtDM_Viewer-parser-parser-pro-distclean: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers-distclean FORCE
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE) distclean
sub-caQtDM_Viewer-parser-parser-pro-install_subtargets: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers-install_subtargets FORCE
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE) install
sub-caQtDM_Viewer-parser-parser-pro-uninstall_subtargets: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers-uninstall_subtargets FORCE
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE) uninstall
caQtDM_Viewer/parserEDM/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) caQtDM_Viewer/parserEDM/ || $(MKDIR) caQtDM_Viewer/parserEDM/ 
	cd caQtDM_Viewer/parserEDM/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Viewer/parserEDM/parserEDM.pro -o $(MAKEFILE)
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) caQtDM_Viewer/parserEDM/ || $(MKDIR) caQtDM_Viewer/parserEDM/ 
	cd caQtDM_Viewer/parserEDM/ && $(QMAKE) /afs/psi.ch/user/m/mohacsi_i/Documents/caqtdm/caQtDM_Viewer/parserEDM/parserEDM.pro -o $(MAKEFILE)
sub-caQtDM_Viewer-parserEDM-parserEDM-pro: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers FORCE
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE)
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-make_default: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers-make_default FORCE
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE) 
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-make_first: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers-make_first FORCE
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE) first
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-all: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers-all FORCE
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE) all
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-clean: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers-clean FORCE
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE) clean
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-distclean: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers-distclean FORCE
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE) distclean
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-install_subtargets: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers-install_subtargets FORCE
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE) install
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-uninstall_subtargets: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers-uninstall_subtargets FORCE
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: all.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		caQtDM_Viewer/qtdefs.pri \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile all.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
caQtDM_Viewer/qtdefs.pri:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile all.pro

qmake_all: sub-caQtDM_QtControls-qmake_all sub-caQtDM_Lib-qmake_all sub-caQtDM_Viewer-qmake_all sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-qmake_all sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-qmake_all sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-qmake_all sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-qmake_all sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-qmake_all sub-caQtDM_Parsers-qmake_all sub-caQtDM_Viewer-parser-parser-pro-qmake_all sub-caQtDM_Viewer-parserEDM-parserEDM-pro-qmake_all FORCE

make_default: sub-caQtDM_QtControls-make_default sub-caQtDM_Lib-make_default sub-caQtDM_Viewer-make_default sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-make_default sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-make_default sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-make_default sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-make_default sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-make_default sub-caQtDM_Parsers-make_default sub-caQtDM_Viewer-parser-parser-pro-make_default sub-caQtDM_Viewer-parserEDM-parserEDM-pro-make_default FORCE
make_first: sub-caQtDM_QtControls-make_first sub-caQtDM_Lib-make_first sub-caQtDM_Viewer-make_first sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-make_first sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-make_first sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-make_first sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-make_first sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-make_first sub-caQtDM_Parsers-make_first sub-caQtDM_Viewer-parser-parser-pro-make_first sub-caQtDM_Viewer-parserEDM-parserEDM-pro-make_first FORCE
all: sub-caQtDM_QtControls-all sub-caQtDM_Lib-all sub-caQtDM_Viewer-all sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-all sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-all sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-all sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-all sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-all sub-caQtDM_Parsers-all sub-caQtDM_Viewer-parser-parser-pro-all sub-caQtDM_Viewer-parserEDM-parserEDM-pro-all FORCE
clean: sub-caQtDM_QtControls-clean sub-caQtDM_Lib-clean sub-caQtDM_Viewer-clean sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-clean sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-clean sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-clean sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-clean sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-clean sub-caQtDM_Parsers-clean sub-caQtDM_Viewer-parser-parser-pro-clean sub-caQtDM_Viewer-parserEDM-parserEDM-pro-clean FORCE
distclean: sub-caQtDM_QtControls-distclean sub-caQtDM_Lib-distclean sub-caQtDM_Viewer-distclean sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-distclean sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-distclean sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-distclean sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-distclean sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-distclean sub-caQtDM_Parsers-distclean sub-caQtDM_Viewer-parser-parser-pro-distclean sub-caQtDM_Viewer-parserEDM-parserEDM-pro-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-caQtDM_QtControls-install_subtargets sub-caQtDM_Lib-install_subtargets sub-caQtDM_Viewer-install_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-install_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-install_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-install_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-install_subtargets sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-install_subtargets sub-caQtDM_Parsers-install_subtargets sub-caQtDM_Viewer-parser-parser-pro-install_subtargets sub-caQtDM_Viewer-parserEDM-parserEDM-pro-install_subtargets FORCE
uninstall_subtargets: sub-caQtDM_QtControls-uninstall_subtargets sub-caQtDM_Lib-uninstall_subtargets sub-caQtDM_Viewer-uninstall_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-uninstall_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-uninstall_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-uninstall_subtargets sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-uninstall_subtargets sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-uninstall_subtargets sub-caQtDM_Parsers-uninstall_subtargets sub-caQtDM_Viewer-parser-parser-pro-uninstall_subtargets sub-caQtDM_Viewer-parserEDM-parserEDM-pro-uninstall_subtargets FORCE

sub-caQtDM_QtControls-check: caQtDM_QtControls/$(MAKEFILE) sub-caQtDM_Parsers-check
	cd caQtDM_QtControls/ && $(MAKE) -f $(MAKEFILE) check
sub-caQtDM_Lib-check: caQtDM_Lib/$(MAKEFILE) sub-caQtDM_QtControls-check
	cd caQtDM_Lib/ && $(MAKE) -f $(MAKEFILE) check
sub-caQtDM_Viewer-check: caQtDM_Viewer/$(MAKEFILE) sub-caQtDM_QtControls-check sub-caQtDM_Lib-check sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-check sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-check sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-check sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-check sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-check
	cd caQtDM_Viewer/ && $(MAKE) -f $(MAKEFILE) check
sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-check: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_controllers sub-caQtDM_QtControls-check sub-caQtDM_Lib-check
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_controllers check
sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-check: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_graphics sub-caQtDM_QtControls-check sub-caQtDM_Lib-check
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_graphics check
sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-check: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_monitors sub-caQtDM_QtControls-check sub-caQtDM_Lib-check
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_monitors check
sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-check: caQtDM_QtControls/plugins/$(MAKEFILE).qtcontrols_utilities sub-caQtDM_QtControls-check sub-caQtDM_Lib-check
	cd caQtDM_QtControls/plugins/ && $(MAKE) -f $(MAKEFILE).qtcontrols_utilities check
sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-check: caQtDM_Lib/caQtDM_Plugins/$(MAKEFILE).csplugins sub-caQtDM_Lib-check
	cd caQtDM_Lib/caQtDM_Plugins/ && $(MAKE) -f $(MAKEFILE).csplugins check
sub-caQtDM_Parsers-check: caQtDM_Parsers/$(MAKEFILE)
	cd caQtDM_Parsers/ && $(MAKE) -f $(MAKEFILE) check
sub-caQtDM_Viewer-parser-parser-pro-check: caQtDM_Viewer/parser/$(MAKEFILE) sub-caQtDM_Parsers-check
	cd caQtDM_Viewer/parser/ && $(MAKE) -f $(MAKEFILE) check
sub-caQtDM_Viewer-parserEDM-parserEDM-pro-check: caQtDM_Viewer/parserEDM/$(MAKEFILE) sub-caQtDM_Parsers-check
	cd caQtDM_Viewer/parserEDM/ && $(MAKE) -f $(MAKEFILE) check
check: sub-caQtDM_QtControls-check sub-caQtDM_Lib-check sub-caQtDM_Viewer-check sub-caQtDM_QtControls-plugins-qtcontrols_controllers-pro-check sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-check sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-check sub-caQtDM_QtControls-plugins-qtcontrols_utilities-pro-check sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-check sub-caQtDM_Parsers-check sub-caQtDM_Viewer-parser-parser-pro-check sub-caQtDM_Viewer-parserEDM-parserEDM-pro-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

