#!/bin/sh
export QTCONTROLS_LIBS=`pwd`//caQtDM_Binaries
export QTBASE=${QTCONTROLS_LIBS}
export PATH=.:$QTBASE:$PATH
export LD_LIBRARY_PATH=.:$QTBASE:$LD_LIBRARY_PATH
export QT_PLUGIN_PATH=$QTBASE
export CAQTDM_DISPLAY_PATH="`pwd`/caQtDM_Tests ../caQtDM_Tests/hipaFiles ../caQtDM_Tests/sfFiles"
echo $CAQTDM_DISPLAY_PATH
export EPICS_CA_MAX_ARRAY_BYTES=40000000
export CAQTDM_OPTIMIZE_EPICS3CONNECTIONS=true
$QTBASE/caQtDM -style plastique $*&
