#!/bin/sh

export QTCONTROLS_LIBS=`pwd`/caQtDM_Binaries
export QTBASE=${QTCONTROLS_LIBS}
export PATH=.:$QTBASE:$PATH
export QT_PLUGIN_PATH=$QTBASE
export CAQTDM_DISPLAY_PATH=`pwd`/caQtDM_Tests
$QTBASE/caQtDM -style plastique $*&
