#ifndef CAQTDM_PLUGINS_GLOBAL_H
#define CAQTDM_PLUGINS_GLOBAL_H

#include "qtdefinitions.h"

#if defined(UNIT_TESTING)
#define CAQTDM_PLUGINSSHARED_EXPORT
#else
#if defined(_MSC_VER)
#if defined(CAQTDM_PLUGIN_LIBRARY)
#define CAQTDM_PLUGINSSHARED_EXPORT __declspec(dllexport)
#else
#define CAQTDM_PLUGINSSHARED_EXPORT __declspec(dllimport)
#endif
#else
#define CAQTDM_PLUGINSSHARED_EXPORT
#endif
#endif

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(archiveHTTPLog)
Q_DECLARE_LOGGING_CATEGORY(archiveSFLog)
Q_DECLARE_LOGGING_CATEGORY(bsreadLog)
Q_DECLARE_LOGGING_CATEGORY(demoLog)
Q_DECLARE_LOGGING_CATEGORY(environmentLog)
Q_DECLARE_LOGGING_CATEGORY(epics3Log)
Q_DECLARE_LOGGING_CATEGORY(epics4Log)
Q_DECLARE_LOGGING_CATEGORY(gpsLog)
Q_DECLARE_LOGGING_CATEGORY(modbusLog)
Q_DECLARE_LOGGING_CATEGORY(opcuaLog)
Q_DECLARE_LOGGING_CATEGORY(pvxsLog)

#endif // CAQTDM_PLUGINS_GLOBAL_H
